#!/usr/bin/env bash

# https://github.com/aktau/github-release

set -eu

# custom setting
bin="bin/tcpsniffer"

# created setting
tag=$(git tag -l | sort -V | tail -1)
user="maiha"
repo=$(basename `git rev-parse --show-toplevel`)
body=`sha256sum $bin`

cmd="github-release upload -u $user -r $repo -t $tag -n $(basename $bin) -f $bin"

# env
: ${GITHUB_TOKEN?"Need to set GITHUB_TOKEN"}

# print cmd as dryrun
echo $cmd

# confirmation
read -p "Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo    # (optional) move to a new line
  $cmd
fi
